# Copyright (c) 2014 Alexander Lamaison <alexander.lamaison@gmail.com>
# Copyright (c) 2014 Ruslan Baratov <ruslan_baratov@yahoo.com>
#
# Redistribution and use in source and binary forms,
# with or without modification, are permitted provided
# that the following conditions are met:
#
#   Redistributions of source code must retain the above
#   copyright notice, this list of conditions and the
#   following disclaimer.
#
#   Redistributions in binary form must reproduce the above
#   copyright notice, this list of conditions and the following
#   disclaimer in the documentation and/or other materials
#   provided with the distribution.
#
#   Neither the name of the copyright holder nor the names
#   of any other contributors may be used to endorse or
#   promote products derived from this software without
#   specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND
# CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES,
# INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
# OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR
# CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
# SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
# BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
# SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
# WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
# NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE
# USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY
# OF SUCH DAMAGE.


# Mac OS X (https://github.com/travis-ci-tester/toolchain-table)

language:
    - objective-c

env:
    - TOOLCHAIN=default TEST="--test" CONFIG=Release ENABLE_ZLIB_COMPRESSION=ON
    - TOOLCHAIN=default TEST="--test" CONFIG=Debug ENABLE_ZLIB_COMPRESSION=ON
    - TOOLCHAIN=libcxx TEST="--test" CONFIG=Release ENABLE_ZLIB_COMPRESSION=ON
    - TOOLCHAIN=libcxx TEST="--test" CONFIG=Debug ENABLE_ZLIB_COMPRESSION=ON
    - TOOLCHAIN=clang-libstdcxx TEST="--test" CONFIG=Release ENABLE_ZLIB_COMPRESSION=ON
    - TOOLCHAIN=clang-libstdcxx TEST="--test" CONFIG=Debug ENABLE_ZLIB_COMPRESSION=ON
    - TOOLCHAIN=xcode TEST="--test" CONFIG=Release ENABLE_ZLIB_COMPRESSION=ON
    - TOOLCHAIN=xcode TEST="--test" CONFIG=Debug ENABLE_ZLIB_COMPRESSION=ON
    - TOOLCHAIN=gcc TEST="--test" CONFIG=Release ENABLE_ZLIB_COMPRESSION=ON
    - TOOLCHAIN=gcc TEST="--test" CONFIG=Debug ENABLE_ZLIB_COMPRESSION=ON
    - TOOLCHAIN=ios-nocodesign EXTRA="--iossim" CONFIG=Release ENABLE_ZLIB_COMPRESSION=ON
    - TOOLCHAIN=ios-nocodesign EXTRA="--iossim" CONFIG=Debug ENABLE_ZLIB_COMPRESSION=ON
        # Extra cmake modules needed for iOS testing:
        # * https://github.com/ruslo/sugar/tree/master/cmake/core#sugar_add_ios_gtest
    - TOOLCHAIN=analyze TEST="--test" CONFIG=Release ENABLE_ZLIB_COMPRESSION=ON
    - TOOLCHAIN=analyze TEST="--test" CONFIG=Debug ENABLE_ZLIB_COMPRESSION=ON
    - TOOLCHAIN=default TEST="--test" CONFIG=Release ENABLE_ZLIB_COMPRESSION=OFF
    - TOOLCHAIN=default TEST="--test" CONFIG=Debug ENABLE_ZLIB_COMPRESSION=OFF
    - TOOLCHAIN=libcxx TEST="--test" CONFIG=Release ENABLE_ZLIB_COMPRESSION=OFF
    - TOOLCHAIN=libcxx TEST="--test" CONFIG=Debug ENABLE_ZLIB_COMPRESSION=OFF
    - TOOLCHAIN=clang-libstdcxx TEST="--test" CONFIG=Release ENABLE_ZLIB_COMPRESSION=OFF
    - TOOLCHAIN=clang-libstdcxx TEST="--test" CONFIG=Debug ENABLE_ZLIB_COMPRESSION=OFF
    - TOOLCHAIN=xcode TEST="--test" CONFIG=Release ENABLE_ZLIB_COMPRESSION=OFF
    - TOOLCHAIN=xcode TEST="--test" CONFIG=Debug ENABLE_ZLIB_COMPRESSION=OFF
    - TOOLCHAIN=gcc TEST="--test" CONFIG=Release ENABLE_ZLIB_COMPRESSION=OFF
    - TOOLCHAIN=gcc TEST="--test" CONFIG=Debug ENABLE_ZLIB_COMPRESSION=OFF
    - TOOLCHAIN=ios-nocodesign EXTRA="--iossim" CONFIG=Release ENABLE_ZLIB_COMPRESSION=OFF
    - TOOLCHAIN=ios-nocodesign EXTRA="--iossim" CONFIG=Debug ENABLE_ZLIB_COMPRESSION=OFF
        # Extra cmake modules needed for iOS testing:
        # * https://github.com/ruslo/sugar/tree/master/cmake/core#sugar_add_ios_gtest
    - TOOLCHAIN=analyze TEST="--test" CONFIG=Release ENABLE_ZLIB_COMPRESSION=OFF
    - TOOLCHAIN=analyze TEST="--test" CONFIG=Debug ENABLE_ZLIB_COMPRESSION=OFF

install:
    - brew install cmake
    - brew install python3
    # install cmake toolchains and script
    - POLLY_VERSION="0.6.2"
    - wget "https://github.com/ruslo/polly/archive/v${POLLY_VERSION}.tar.gz"
    - tar xf "v${POLLY_VERSION}.tar.gz"
    - export PATH="`pwd`/polly-${POLLY_VERSION}/bin:${PATH}"
    # -- end
    # install cmake
    - CMAKE_VERSION="3.1.0-rc2-ruslo"
    - wget "https://github.com/ruslo/CMake/archive/v${CMAKE_VERSION}.tar.gz"
    - openssl sha1 "v${CMAKE_VERSION}.tar.gz"
    - tar xf "v${CMAKE_VERSION}.tar.gz"
    - cd "CMake-${CMAKE_VERSION}"
    -   build.py --install --toolchain default --config Release --fwd "CMAKE_USE_SYSTEM_CURL=YES"
    -   export PATH="`pwd`/_install/default/bin:${PATH}"
    - cd ..
    # -- end
    # verify installed cmake
    - which cmake
    - cmake --version
    # -- end

script:
    # TODO ADDRESS_SIZE=64/32
    # TODO BUILD_SHARED_LIBS=ON/OFF
    # TODO CRYPTO_BACKEND=Libgcrypt
    - build.py --toolchain ${TOOLCHAIN} --config ${CONFIG} --verbose --fwd CRYPTO_BACKEND=OpenSSL ENABLE_ZLIB_COMPRESSION=${ENABLE_ZLIB_COMPRESSION} HUNTER_ENABLED=ON ${TEST} ${EXTRA}
